import { chromium } from '@playwright/test';
import { mkdir, writeFile } from 'node:fs/promises';
import assert from 'node:assert/strict';

const artifacts = new URL('./artifacts/', import.meta.url);
await mkdir(artifacts, { recursive: true });
const browser = await chromium.launch({ headless: true });
const page = await browser.newPage({ viewport: { width: 1440, height: 1100 }, deviceScaleFactor: 1 });
const errors = [];
page.on('pageerror', error => errors.push(error.message));
const url = 'http://127.0.0.1:4173/examples/directions/product-study/?qa';
await page.goto(url);
await page.waitForFunction(() => window.productQA && !window.productQA.state().fallback);
await page.screenshot({ path: new URL('desktop-exterior.png', artifacts).pathname, fullPage: true });
const initial = await page.evaluate(() => window.productQA.state());
await page.waitForTimeout(350);
assert.equal((await page.evaluate(() => window.productQA.state())).renderCount, initial.renderCount, 'idle renderer should remain still');
await page.getByRole('button', { name: 'Exploded', exact: true }).click();
await page.waitForFunction(() => window.productQA.state().expansion === 1 && !window.productQA.state().animating);
await page.screenshot({ path: new URL('desktop-expanded.png', artifacts).pathname, fullPage: true });
await page.getByRole('button', { name: '03 Spacer Axial spacing' }).focus();
await page.keyboard.press('Enter');
assert.equal(await page.evaluate(() => window.productQA.state().selected), 'spacer');
await page.getByRole('button', { name: 'Reset' }).click();
await page.waitForFunction(() => window.productQA.state().expansion === 0 && !window.productQA.state().animating);
assert.equal(await page.evaluate(() => window.productQA.state().selected), null);
await page.getByRole('button', { name: 'Exploded', exact: true }).click();
await page.waitForTimeout(150);
await page.getByRole('button', { name: 'Exterior', exact: true }).click();
await page.waitForFunction(() => window.productQA.state().expansion === 0 && !window.productQA.state().animating);
await page.locator('#spread').focus();
await page.keyboard.press('End');
await page.waitForFunction(() => window.productQA.state().expansion === 1);
const point = await page.evaluate(() => window.productQA.project('front'));
await page.mouse.click(point.x, point.y);
assert.equal(await page.evaluate(() => window.productQA.state().selected), 'front', 'actual canvas pick should select the front lens');
const expanded = await page.evaluate(() => window.productQA.state());
assert.ok(expanded.positions.rear < expanded.positions.spacer && expanded.positions.spacer < expanded.positions.front && expanded.positions.front < expanded.positions.retainer);
const beforeDrag = expanded.selected;
await page.mouse.move(point.x, point.y); await page.mouse.down(); await page.mouse.move(point.x + 65, point.y + 12, { steps: 6 }); await page.mouse.up();
assert.equal(await page.evaluate(() => window.productQA.state().selected), beforeDrag, 'rotation should not trigger a selection');
await page.getByRole('button', { name: 'Change view' }).focus(); await page.keyboard.press('Enter');
assert.equal(await page.evaluate(() => window.productQA.state().view), 1);
const desktopOverflow = await page.evaluate(() => document.documentElement.scrollWidth > innerWidth);
assert.equal(desktopOverflow, false);

await page.setViewportSize({ width: 390, height: 844 });
await page.getByRole('button', { name: 'Reset' }).click();
await page.waitForFunction(() => window.productQA.state().expansion === 0 && !window.productQA.state().animating);
await page.screenshot({ path: new URL('mobile-exterior.png', artifacts).pathname, fullPage: true });
await page.getByRole('button', { name: 'Exploded', exact: true }).click();
await page.waitForFunction(() => window.productQA.state().expansion === 1 && !window.productQA.state().animating);
await page.screenshot({ path: new URL('mobile-expanded.png', artifacts).pathname, fullPage: true });
assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
assert.equal(await page.locator('canvas').evaluate(element => getComputedStyle(element).touchAction), 'pan-y');
await page.getByRole('button', { name: 'Enable touch rotation' }).click();
assert.equal(await page.locator('canvas').evaluate(element => getComputedStyle(element).touchAction), 'none');
await page.getByRole('button', { name: 'Disable touch rotation' }).click();
await page.setViewportSize({ width: 320, height: 740 });
assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);

await page.emulateMedia({ reducedMotion: 'reduce' });
await page.getByRole('button', { name: 'Exterior', exact: true }).click();
const reduced = await page.evaluate(() => window.productQA.state());
assert.equal(reduced.expansion, 0); assert.equal(reduced.animating, false);
await page.evaluate(() => window.productQA.loseContext());
await page.waitForFunction(() => window.productQA.state().fallback);
await page.locator('[data-part="front"]').click();
assert.equal(await page.locator('#detail-title').textContent(), 'Front lens');
assert.equal(await page.locator('canvas').isVisible(), false);
assert.equal(await page.locator('#fallback svg').isVisible(), true);
await page.waitForTimeout(150);
await page.screenshot({ path: new URL('fallback.png', artifacts).pathname, fullPage: true });
await page.evaluate(() => window.productQA.dispose());
assert.equal(await page.locator('canvas').count(), 0);
assert.equal(errors.length, 0, errors.join('\n'));
const report = { checkedAt: new Date().toISOString(), browser: await browser.version(), three: initial.revision, idle: true, keyboardSelection: true, reset: true, interrupt: true, sliderKeyboard: true, canvasPick: true, dragNotSelect: true, viewKeyboard: true, overflow: { desktop: false, mobile390: false, mobile320: false }, touchMode: true, reducedMotion: true, contextLoss: true, disposal: true, expandedRendering: expanded.renderer, pageErrors: errors };
await writeFile(new URL('browser-report.json', artifacts), JSON.stringify(report, null, 2) + '\n');
console.log(JSON.stringify(report, null, 2));
await browser.close();
